#!/sbin/sh
# Copyright 2016 Antoine GRAVELOT
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#	Author : Nevax
#

bp=/system/build.prop
dpi=$2

if [ ! -f $bp ]; then
  echo "Unable to find build.prop file, make sure your system partition is mounted."
  exit
fi

case $1 in
  set)
  case $dpi in
    3[5-9][0-9]|4[0-9][0-9]|500)
    if grep -qr ro.sf.lcd_density= $bp ; then
      echo "DPI is set, change value to $dpi"
      sed -i "s/ro.sf.lcd_density=.*/ro.sf.lcd_density=$dpi/" $bp
    else
      echo "DPI value is not set in build.prop, add $dpi dpi value."
      echo ro.sf.lcd_density=$dpi >> $bp
    fi
    ;;
    *)
    echo "Please select a value between 350 and 500."
    ;;
    esac
  ;;
  reset)
  echo "DPI value has been reset"
  sed -i "s/ro.sf.lcd_density=.*//" $bp
  ;;
  *)
  echo "Wrong settings"
  echo "HELP:"
  echo ""
  echo "dpi set 400"
  echo "    Set the DPI value to 400"
  echo ""
  echo "dpi reset"
  echo "     Remove all the DPI settings in your current build prop, reset to default"
  ;;
  esac

echo ""
echo ""
echo "FreedomOS ROM DPI Changer, by NevaX1 aka Nevax aka Antoine GRAVELOT"
echo "Goodbay!"
