#!/system/bin/sh
#
# ARISE Sound Systems™
#
# Deuteronomy™
#
# arisesound_setprop
#
# www.arisesound.com


## Asus™ Zenfone 3 Ultra Audio ##

#
setprop media.stagefright.enable-player true
setprop media.stagefright.enable-http true
setprop media.stagefright.enable-aac true
setprop media.stagefright.enable-qcp true
setprop media.stagefright.enable-scan true
setprop mm.enable.smoothstreaming true
setprop mmp.enable.3g2 true
setprop media.aac_51_output_enabled true
setprop audio.offload.track.enable false
setprop audio.deep_buffer.media true
setprop audio.offload.gapless.enabled true
setprop audio.offload.multiple.enabled false
setprop audio.safx.pbe.enabled true
setprop audio.pp.asphere.enabled false
setprop audio.offload.pcm.16bit.enable true
setprop audio.offload.pcm.24bit.enable true
setprop audio.dolby.ds2.enabled true
setprop audio.dolby.ds2.hardbypass true
#


## Huawei™ Multi-device Audio ##

#
setprop mm.enable.qcom_parser 1048575
setprop audio.parser.ip.buffer.size 262144
setprop ro.config.hw_music_lp true
setprop ro.config.hw_dts true
setprop ro.config.hw_sws true
setprop ro.config.sws_version sws3
setprop ro.config.swsAlwaysActiveForSPK true
setprop ro.config.hw_dts_settings true
setprop ro.config.hw_media_flags 3
setprop ro.config.hpx_support true
setprop ro.config.hw_dolby true
setprop ro.config.hw_audio_plus true
setprop audio.musicfx.bassboost.max 500
setprop audio.musicfx.virtualizer.max 500
setprop use.qti.sw.alac.decoder true
setprop use.qti.sw.ape.decoder true
setprop flac.sw.decoder.24bit.support true
#


## ViPER4Arise™ Audio ##

#
setprop tunnel.decode false
setprop lpa.decode false
setprop lpa.use-stagefright false
#


## Miscellaneous Audio ##

#
#Hi-Res option for PowerAmp
setprop ro.lenovo.hifi_support true
setprop persist.bt.enableAptXHD true
#


exit 0
