#!/system/bin/sh
#
# ARISE Sound Systems™
#
# Deuteronomy™
#
# arisesound_setprop
#
# www.arisesound.com




## Asus™ Zenfone 3 Ultra Audio ##

#
#codecs:(PARSER_)AAC AC3 AMR_NB AMR_WB ASF AVI DTS FLV 3GP 3G2 MKV MP2PS MP2TS MP3 OGG QCP WAV FLAC AIFF APE
setprop mm.enable.qcom_parser 982015

#parser input buffer size(256kb) in byte stream mode
setprop audio.parser.ip.buffer.size 262144

setprop media.stagefright.enable-player true
setprop media.stagefright.enable-http true
setprop media.stagefright.enable-aac true
setprop media.stagefright.enable-qcp true
setprop media.stagefright.enable-scan true
setprop qcom.hw.aac.encoder true
setprop mm.enable.smoothstreaming true
setprop av.debug.disable.pers.cache true
setprop mmp.enable.3g2 true
setprop media.aac_51_output_enabled true
setprop audio.offload.track.enable false
setprop audio.deep_buffer.media true
setprop audio.offload.gapless.enabled true
setprop audio.offload.multiple.enabled false
setprop audio.safx.pbe.enabled true
setprop audio.pp.asphere.enabled false
#setprop ro.asus.audio.feature ar101
#setprop ro.asus.audiowizard.config 1
setprop audio.offload.pcm.16bit.enable true
setprop audio.offload.pcm.24bit.enable true
setprop audio.dolby.ds2.enabled true
setprop audio.dolby.ds2.hardbypass true
#

## Huawei™ MediaPad M3 Audio ##

#
setprop ro.config.hw_dts true
setprop ro.config.hw_sws true
setprop ro.config.sws_version sws3
setprop ro.audio.monitorOrientation true
setprop ro.audio.monitorRotation true
setprop ro.config.hw_media_flags 3
setprop ro.config.widevine_level3 true
setprop drm.service.enabled true
setprop ro.config.keyguard_audio_video true
#

## ViPER4Arise™ Audio ##

#
setprop tunnel.decode false
setprop lpa.decode false
setprop lpa.use-stagefright false
#

## Miscellaneous Audio ##

#
#Hi-Res option for PowerAmp
setprop ro.lenovo.hifi_support true
#

exit 0
